### ISSUE TITLE
Feature: Support Mixed-case Checksum address encoding

### ISSUE THREAD

**Issue by sambacha** [paulmillr/micro-eth-signer#23]
See the EIP Specification here: ~~https://github.com/ethereum/ercs/blob/master/ERCS/erc-55.md~~ https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md 

EIP-1191[^1]: This uses ChainId to encode mixed-case checksumming to addresses, allow the same address to be differentiated based on the encoding of character case based on ChainId

[^1]: Correct EIP is 1191, not 55

**Comment by paulmillr** [comment]
This one? erc-55 doesn't mention anything about chainid

https://github.com/paulmillr/micro-eth-signer/blob/3208304b1c74820e405911775a4fb3cd060e581f/src/address.ts#L37-L46

**Comment by sambacha** [comment]
whoops, meant this one sorry! https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md

**Comment by sambacha** [comment]
example:  
  
EIP-1191 Checksum for mevETH

```
0x24aE2dA0F361AA4bE46B48EB19c91e02c5E4F27e
```

Normal Checksum

```
0x24Ae2dA0f361AA4BE46b48EB19C91e02c5e4f27E
```

**Comment by paulmillr** [comment]
That seems useful.

**Comment by paulmillr** [comment]
c8a86a6

**Comment by sambacha** [comment]
Hell yeah, thanks for getting this done so quickly!

**Comment by ricmoo** [comment]
I’ve just been made aware of these changes.

EIP-1191 is a derelict EIP, has been removed and discouraged from existing libraries and should not be introduced.

Web3.js and EthereumJS (back in 2021) had to wait until a major version to remove it, which I would suspect would be the same here.

The [discussion-to link](https://github.com/ethereum/EIPs/issues/1121) in the EIP covers much of the issues, as well as helps give context why it was never moved from last call to final. It was contention and breaks (entirely) backwards compatibility in the address format, which EIP-155 tried so desperately to maintain.

I would love to carry on this discussion further if necessary and interested though. I thought the EIP had finally been defeated, but now see people talking about it again, so wanted to speak up. :)

**Comment by paulmillr** [comment]
@sambacha thoughts on reverting this?
