### ISSUE TITLE
Support EIP-712

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/micro-eth-signer#26]
`EIP-712` Typed structured data hashing and signing (`eth_signTypedData_v4`) is required to perform token swap on pancakeswap.

Existing implementation using `@noble/hashes` https://github.com/Mrtenz/eip-712

**Comment by mahnunchik** [comment]
An example on walletconnect website https://docs.walletconnect.com/advanced/multichain/rpc-reference/ethereum-rpc#eth_signtypeddata

**Comment by paulmillr** [comment]
How popular is EIP-712? Have you analyzed this?

**Comment by mahnunchik** [comment]
EIP-712 is used in all token swaps on pancakeswap and uniswap. Some documentation:

* https://support.uniswap.org/hc/en-us/articles/8120520483085-What-is-an-approval-transaction
* https://docs.walletconnect.com/advanced/multichain/rpc-reference/ethereum-rpc

I think other decentralized exchanges use this mechanism too.

Soon we will have our own usage statistics.

**Comment by mahnunchik** [comment]
Current solution https://github.com/CoinSpace/cs-evm-wallet/blob/master/lib/EvmWallet.js#L557-L583

**Comment by eshaan7** [comment]
EIP-712 has become the de facto standard for Typed Data Signing in Ethereum and EVM systems. This would definitely be a good addition to this package.

Ethers.js provides a good EIP-712 implementation but I was required to roll my own implementation of it for a private project using only noble cryptography packages without any dependency on ethers. It's essentially a drop-in replacement for the [`TypedDataEncoder`](https://docs.ethers.org/v5/api/utils/hashing/#TypedDataEncoder) class provided by ethers.

I'd be happy to re-purpose my implementation and raise a PR with it.

cc: @paulmillr
