### ISSUE TITLE
Speed of sign

### ISSUE THREAD

**Issue by berktaylan** [paulmillr/micro-eth-signer#7]
Hello,

I was expecting this library to make sign progress faster, but somehow its 20x slower than other libraries. (30-40ms)

Any workaround on this ? I was expecting lower than <1 ms, because there are other libraries can handle sign in 2ms.
Am i doing something wrong ?

**Comment by paulmillr** [comment]
I have added benchmark in https://github.com/paulmillr/micro-eth-signer/commit/9be401599089aacbdbd486f8f437e3ce1c92a5e8

It is fast enough:

   tx.sign() create x 3,773 ops/sec @ 265μs/op

To execute the benchmark, do `npm install && npm run bench`

**Comment by berktaylan** [comment]
I ran the benchmark and i almost got the same results.

But somehow when i try to benchmark it with performance.now() i goet result like 20+ms

`21.73429200053215
Transaction {
  hardfork: 'london',
  hex: '0x02f86f01010185174876e80082520894df90dea0e0bf5ca6d2a7f0cb86874ba6714f463e880de0b6b3a764000080c080a07b135cec49f168ce86a951df186b2ce2d8ee682ade7e3e819346a29eb908a4f4a0286fc6d85e581336b75604e3c9056e5e66a92f8f35533825f51cdea8662db82a',
  type: 'eip1559',
  raw: {
    chainId: '0x01',
    nonce: '0x01',
    maxPriorityFeePerGas: '0x01',
    maxFeePerGas: '0x174876e800',
    gasLimit: '0x5208',
    to: '0xdf90dea0e0bf5ca6d2a7f0cb86874ba6714f463e',
    value: '0x0de0b6b3a7640000',
    data: '',
    accessList: [],
    yParity: '',
    r: '0x7b135cec49f168ce86a951df186b2ce2d8ee682ade7e3e819346a29eb908a4f4',
    s: '0x286fc6d85e581336b75604e3c9056e5e66a92f8f35533825f51cdea8662db82a'
  },
  isSigned: true
}
`

`const signer = require('..');

async function erden () {
  const getTx = () => new signer.Transaction({
    to: '0xdf90dea0e0bf5ca6d2a7f0cb86874ba6714f463e',
    maxFeePerGas: 100n * 10n ** 9n, // 100 gwei in wei
    value: 10n ** 18n, // 1 eth in wei
    nonce: 1,
    maxPriorityFeePerGas: 1,
    chainId: 1
  });
  const tx = getTx();
  const privateKey = '6b911fd37cdf5c81d4c0adb1ab7fa822ed253ab0ad9aa18d77257c88b29b718e';
  let time1 = performance.now();
  var test1 = await tx.sign(privateKey);
  let time2 = performance.now()-time1;
  console.log(time2);
  console.log(test1);
};

erden();`

**Comment by paulmillr** [comment]
First signature will take 20+ ms because of noble-secp precomputes generation. You can do it manually by executing `utils.precompute()` in noble-secp in the start of your app. Search noble-secp readme for `utils.precompute`.

**Comment by berktaylan** [comment]
Thanks for the explain,

So instead of utils.precompute() i ran 2x sign function , i see good improvement, but its still 3.5x slower than the benchmark results.

```
0.8618749976158142
```

```
const signer = require('..');

async function erden () {
  const getTx = () => new signer.Transaction({
    to: '0xdf90dea0e0bf5ca6d2a7f0cb86874ba6714f463e',
    maxFeePerGas: 100n * 10n ** 9n, // 100 gwei in wei
    value: 10n ** 18n, // 1 eth in wei
    nonce: 1,
    maxPriorityFeePerGas: 1,
    chainId: 1
  });
  const tx = getTx();
  const privateKey = '6b911fd37cdf5c81d4c0adb1ab7fa822ed253ab0ad9aa18d77257c88b29b718e';

  var test1 = await tx.sign(privateKey)
 

  var test1 = await tx.sign(privateKey);



  let time5 = performance.now();
  var test1 = await tx.sign(privateKey);
  let time6 = performance.now()-time5;
  console.log(time6);

};

erden();
```

**Comment by paulmillr** [comment]
1. performance.now() can be slower than Date.now(), because it traces all function calls.
2. Is the environment you're executing the functions the same? E.g. both benchmark and your function use the same node.js version? Or, is your version executed in a browser, for example? The browser can be slower.
3. Instead of doing it like that, try

```js
let time5 = Date.now();
await tx.sign(privateKey).then(() => console.log(Date.now() - time5))
```
